### ISSUE TITLE
Hyperopt Placement Group Error

### ISSUE THREAD

**Issue by Alex1996-alt** [StephanAkkerman/Crypto_Forecasting#55]
Hi I tried to run some different Search Space and getting the following Placement Group Error. Could you check this out? Thank you very much for your time

Traceback (most recent call last):
  File "c:\Users\alexo\Desktop\github Copy\src\hyperopt\hyperopt_ray.py", line 414, in <module>
    hyperopt_full()
  File "c:\Users\alexo\Desktop\github Copy\src\hyperopt\hyperopt_ray.py", line 407, in hyperopt_full
    hyperopt_model(model, save_results, coin, time_frame)
  File "c:\Users\alexo\Desktop\github Copy\src\hyperopt\hyperopt_ray.py", line 374, in hyperopt_model
    hyperopt_dataset(model, coin, tf, save_results)
  File "c:\Users\alexo\Desktop\github Copy\src\hyperopt\hyperopt_ray.py", line 330, in hyperopt_dataset
    analysis = hyperopt(
  File "c:\Users\alexo\Desktop\github Copy\src\hyperopt\hyperopt_ray.py", line 295, in hyperopt
    return tuner.fit()
  File "C:\Users\alexo\anaconda3\envs\Crypto\lib\site-packages\ray\tune\tuner.py", line 377, in fit
    return self._local_tuner.fit()
  File "C:\Users\alexo\anaconda3\envs\Crypto\lib\site-packages\ray\tune\impl\tuner_internal.py", line 476, in fit
    analysis = self._fit_internal(trainable, param_space)
  File "C:\Users\alexo\anaconda3\envs\Crypto\lib\site-packages\ray\tune\impl\tuner_internal.py", line 592, in _fit_internal        
    analysis = run(
  File "C:\Users\alexo\anaconda3\envs\Crypto\lib\site-packages\ray\tune\tune.py", line 1001, in run
    runner.cleanup()
  File "C:\Users\alexo\anaconda3\envs\Crypto\lib\site-packages\ray\tune\execution\tune_controller.py", line 1975, in cleanup       
    self._cleanup_trials()
  File "C:\Users\alexo\anaconda3\envs\Crypto\lib\site-packages\ray\tune\execution\tune_controller.py", line 808, in _cleanup_trials
    self._actor_manager.cleanup()
  File "C:\Users\alexo\anaconda3\envs\Crypto\lib\site-packages\ray\air\execution\_internal\actor_manager.py", line 890, in cleanup 
    self._resource_manager.cancel_resource_request(resource_request)
  File "C:\Users\alexo\anaconda3\envs\Crypto\lib\site-packages\ray\air\execution\resources\placement_group.py", line 151, in cancel_resource_request
    future = self._pg_to_staging_future.pop(pg)
KeyError: <ray.util.placement_group.PlacementGroup object at 0x000001CD09252850>

**Comment by StephanAkkerman** [comment]
Did you check if the change in hyperparameters is in the allowed range? Could you tell me what you adjusted?

**Comment by Alex1996-alt** [comment]
Hey sorry I wa about do write you. I had somehow a wrong version of ray now everything seems to work again. Anyway thanks for the quick response

**Comment by Alex1996-alt** [comment]
Yeah I can send you my files I only adjust the coins (less coins) and less models. Getting the error at the beginning of random forest.  Also adjust parallel trials to 5 and Batch Size "batch_size": tune.choice([16, 32, 64, 128]). 
[hyperopt.zip](https://github.com/user-attachments/files/17378639/hyperopt.zip)

**Comment by StephanAkkerman** [comment]
Hmm interesting, I thought the key error might've happened because you added something to the search space. I won't have time to look at it this week, if you need quick answers then I'd suggest asking the people that work with Ray.

**Comment by Alex1996-alt** [comment]
Ok I just testet with the original Search space and didnt change anything else. Getting the same placement Group error unfortunately

**Comment by StephanAkkerman** [comment]
Are you using the ray version that is in the requirements.txt? I had some issues when I tried a newer version

**Comment by Alex1996-alt** [comment]
Yes using ray 2.4.0 just like in the requirements.txt

**Comment by StephanAkkerman** [comment]
> Yeah I can send you my files I only adjust the coins (less coins) and less models. Getting the error at the beginning of random forest. Also adjust parallel trials to 5 and Batch Size "batch_size": tune.choice([16, 32, 64, 128]).

Are you sure the .zip you included has this too? I see now changes compared to the code on GitHub

**Comment by StephanAkkerman** [comment]
And does everything work for the other models and this only happens at random forest?
